# Generated by Django 6.0.6 on 2026-07-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_backfill_grupo_encarregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alunos/'),
        ),
    ]
