# Generated by Django 6.0.6 on 2026-07-05 09:43

from django.db import migrations, models


def preencher_estado_a_partir_de_ativo(apps, schema_editor):
    Aluno = apps.get_model('alunos', 'Aluno')
    Aluno.objects.filter(ativo=True).update(estado='ativo')
    Aluno.objects.filter(ativo=False).update(estado='transferido')


def preencher_ativo_a_partir_de_estado(apps, schema_editor):
    Aluno = apps.get_model('alunos', 'Aluno')
    Aluno.objects.filter(estado='ativo').update(ativo=True)
    Aluno.objects.exclude(estado='ativo').update(ativo=False)


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_aluno_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(
                choices=[('ativo', 'Ativo'), ('transferido', 'Transferido')],
                default='ativo',
                max_length=20,
            ),
        ),
        migrations.RunPython(
            preencher_estado_a_partir_de_ativo,
            preencher_ativo_a_partir_de_estado,
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ativo',
        ),
    ]
