# Generated by Django 6.0.6 on 2026-08-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_aluno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_emissao_bi',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissão do B.I.'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='foto_bi',
            field=models.FileField(blank=True, null=True, upload_to='alunos/bi/', verbose_name='Fotocópia do B.I.'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='local_emissao_bi',
            field=models.CharField(blank=True, help_text='Ex.: Arquivo Nacional de Identificação de Luanda.', max_length=150, verbose_name='Local de emissão do B.I.'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='municipio_natural',
            field=models.CharField(blank=True, max_length=100, verbose_name='Município de naturalidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='naturalidade',
            field=models.CharField(blank=True, help_text='Cidade/comuna de nascimento.', max_length=100, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome da mãe'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do pai'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero_bi',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número do B.I.'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='provincia_natal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Província de naturalidade'),
        ),
    ]
