# Generated by Django 6.0.6 on 2026-08-10 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_aluno_data_emissao_bi_aluno_foto_bi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('aberta', 'Aberta'), ('encaminhada', 'Encaminhada'), ('resolvida', 'Resolvida')], default='aberta', max_length=15)),
                ('encaminhado_para', models.CharField(blank=True, choices=[('diretor_geral', 'Diretor Geral'), ('subdiretor_pedagogico', 'Sub-diretor Pedagógico')], max_length=25)),
                ('observacoes_resolucao', models.TextField(blank=True)),
                ('registada_em', models.DateTimeField(auto_now_add=True)),
                ('encaminhada_em', models.DateTimeField(blank=True, null=True)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, help_text='Educando a que a reclamação se refere, se aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamacoes', to='alunos.aluno')),
                ('encarregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamacoes', to='alunos.encarregado')),
                ('registada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reclamação',
                'verbose_name_plural': 'Reclamações',
                'ordering': ['-registada_em'],
            },
        ),
    ]
