# Generated by Django 6.0.6 on 2026-08-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_reclamacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='encaminhado_para',
            field=models.CharField(blank=True, choices=[('secretaria', 'Secretaria'), ('diretor_geral', 'Diretor Geral'), ('subdiretor_pedagogico', 'Sub-diretor Pedagógico'), ('diretor_turma', 'Diretor de Turma')], max_length=25),
        ),
    ]
