# Generated by Django 6.0.6 on 2026-06-20 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('professores', '0001_initial'),
        ('turmas', '0002_alter_anoletivo_options_alter_classe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={},
        ),
        migrations.RemoveField(
            model_name='professor',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='professor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AtribuicaoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.anoletivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma')),
            ],
            options={
                'unique_together': {('professor', 'disciplina', 'turma', 'ano_letivo')},
            },
        ),
    ]
