# Generated by Django 6.0.6 on 2026-06-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_perfil_tipo_perfil_bi_perfil_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='morada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
