# Generated by Django 6.0.6 on 2026-06-20 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anoletivo',
            options={'ordering': ['-descricao'], 'verbose_name': 'Ano Letivo', 'verbose_name_plural': 'Anos Letivos'},
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['nome']},
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('nome', 'classe', 'ano_letivo')},
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('aberto', models.BooleanField(default=True)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.anoletivo')),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
            },
        ),
    ]
