# Generated by Django 6.0.6 on 2026-06-20 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_aluno_atualizado_em_aluno_criado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificacaoFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='justificacoes/')),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('aprovada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('F', 'Falta'), ('J', 'Justificada'), ('A', 'Atraso')], max_length=1)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
            ],
        ),
    ]
