# Generated by Django 6.0.6 on 2026-06-20 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_aluno_atualizado_em_aluno_criado_em'),
        ('disciplinas', '0001_initial'),
        ('pautas', '0001_initial'),
        ('professores', '0002_alter_professor_options_remove_professor_disciplinas_and_more'),
        ('turmas', '0002_alter_anoletivo_options_alter_classe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='atribuicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.atribuicaodocente'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.periodoacademico'),
        ),
        migrations.AddField(
            model_name='linhapauta',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno'),
        ),
        migrations.AddField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno'),
        ),
        migrations.AddField(
            model_name='nota',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pautas.avaliacao'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='atribuicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.atribuicaodocente'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.periodoacademico'),
        ),
        migrations.AddField(
            model_name='linhapauta',
            name='pauta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pautas.pauta'),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno'),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.anoletivo'),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('atribuicao', 'periodo')},
        ),
    ]
