# Generated by Django 6.0.6 on 2026-06-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
