# Generated by Django 6.0.6 on 2026-07-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministerio', models.CharField(default='Ministério da Educação', max_length=150)),
                ('governo_provincial', models.CharField(blank=True, max_length=150)),
                ('administracao_municipal', models.CharField(blank=True, max_length=150)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do complexo escolar')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='escola/')),
                ('nome_autoridade_visto', models.CharField(blank=True, max_length=150, verbose_name='Nome da autoridade (visto)')),
                ('cargo_autoridade_visto', models.CharField(blank=True, default='Directora Municipal', max_length=100, verbose_name='Cargo da autoridade (visto)')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escola (configuração institucional)',
            },
        ),
    ]
