# Generated by Django 6.0.6 on 2026-08-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='localidade',
            field=models.CharField(blank=True, help_text='Ex.: Calumbo — usada na linha de data/assinatura da pauta final.', max_length=100, verbose_name='Localidade'),
        ),
        migrations.AddField(
            model_name='escola',
            name='nome_subdirector_pedagogico',
            field=models.CharField(blank=True, help_text='Assinatura do rodapé da pauta final ("O SUBDIRECTOR PEDAGÓGICO").', max_length=150, verbose_name='Nome do Subdirector Pedagógico'),
        ),
    ]
