# Generated by Django 6.0.6 on 2026-08-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_escola_localidade_escola_nome_subdirector_pedagogico'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='base_legal_certificado',
            field=models.CharField(blank=True, help_text='Ex.: alínea c) do artigo nº 109º da LBSEE nº 17/16, de 7 de Outubro.', max_length=250, verbose_name='Base legal do certificado'),
        ),
        migrations.AddField(
            model_name='escola',
            name='decreto_criacao',
            field=models.CharField(blank=True, help_text='Ex.: 307/22 de 21 de 04 — usado no texto do certificado.', max_length=150, verbose_name='Decreto de criação da escola'),
        ),
        migrations.AddField(
            model_name='escola',
            name='livro_registo_certificado',
            field=models.CharField(blank=True, help_text='Ex.: nº 44, folha - A.', max_length=150, verbose_name='Livro de registo do certificado'),
        ),
        migrations.AddField(
            model_name='escola',
            name='provincia',
            field=models.CharField(blank=True, help_text='Ex.: Icolo e Bengo — usada no fecho do certificado ("em ..., aos ...").', max_length=100, verbose_name='Província'),
        ),
    ]
