from django.urls import path

from .views import (
    AvaliacaoCreateView,
    AvaliacaoDeleteView,
    AvaliacaoListView,
    AvaliacaoUpdateView,
    NotaCreateView,
    NotaDeleteView,
    NotaListView,
    NotaUpdateView,
    ResultadoDisciplinaCreateView,
    ResultadoDisciplinaDeleteView,
    ResultadoDisciplinaListView,
    ResultadoDisciplinaUpdateView,
    avaliacao_reportar_erro,
    avaliacao_validar,
    baixar_modelo_excel,
    exportar_excel,
    exportar_pdf,
    gerar_resultados,
    importar_excel,
    meus_dependentes,
    minhas_notas,
    notas_dependente,
    pauta_final_exportar_excel,
    pauta_final_exportar_pdf,
    pauta_final_turma,
    pauta_trimestral,
    pauta_turma,
    resultado_reportar_erro,
    resultado_validar,
)


urlpatterns = [
    path('notas/', NotaListView.as_view(), name='nota_lista'),
    path('turma/<int:turma_id>/', pauta_turma, name='pauta_turma'),
    path('nova/', NotaCreateView.as_view(), name='nota_nova'),
    path('<int:pk>/editar/', NotaUpdateView.as_view(), name='nota_editar'),
    path('<int:pk>/excluir/', NotaDeleteView.as_view(), name='nota_excluir'),

    path('avaliacoes/', AvaliacaoListView.as_view(), name='avaliacao_lista'),
    path('avaliacoes/nova/', AvaliacaoCreateView.as_view(), name='avaliacao_nova'),
    path('avaliacoes/<int:pk>/editar/', AvaliacaoUpdateView.as_view(), name='avaliacao_editar'),
    path('avaliacoes/<int:pk>/excluir/', AvaliacaoDeleteView.as_view(), name='avaliacao_excluir'),
    path('avaliacoes/<int:avaliacao_id>/pauta/', pauta_trimestral, name='pauta_trimestral'),
    path('avaliacoes/<int:avaliacao_id>/modelo-excel/', baixar_modelo_excel, name='pauta_modelo_excel'),
    path('avaliacoes/<int:avaliacao_id>/importar-excel/', importar_excel, name='pauta_importar_excel'),
    path('avaliacoes/<int:avaliacao_id>/exportar-excel/', exportar_excel, name='pauta_exportar_excel'),
    path('avaliacoes/<int:avaliacao_id>/exportar-pdf/', exportar_pdf, name='pauta_exportar_pdf'),
    path('avaliacoes/<int:avaliacao_id>/validar/', avaliacao_validar, name='avaliacao_validar'),
    path('avaliacoes/<int:avaliacao_id>/reportar-erro/', avaliacao_reportar_erro, name='avaliacao_reportar_erro'),

    path('resultados/', ResultadoDisciplinaListView.as_view(), name='resultado_lista'),
    path('resultados/novo/', ResultadoDisciplinaCreateView.as_view(), name='resultado_novo'),
    path('resultados/<int:pk>/editar/', ResultadoDisciplinaUpdateView.as_view(), name='resultado_editar'),
    path('resultados/<int:pk>/excluir/', ResultadoDisciplinaDeleteView.as_view(), name='resultado_excluir'),
    path('resultados/gerar/', gerar_resultados, name='gerar_resultados'),
    path('resultados/<int:pk>/validar/', resultado_validar, name='resultado_validar'),
    path('resultados/<int:pk>/reportar-erro/', resultado_reportar_erro, name='resultado_reportar_erro'),
    path('resultados/pauta-final/', pauta_final_turma, name='pauta_final_turma'),
    path('resultados/pauta-final/exportar-excel/', pauta_final_exportar_excel, name='pauta_final_exportar_excel'),
    path('resultados/pauta-final/exportar-pdf/', pauta_final_exportar_pdf, name='pauta_final_exportar_pdf'),

    path('minhas-notas/', minhas_notas, name='minhas_notas'),
    path('dependentes/', meus_dependentes, name='meus_dependentes'),
    path('dependentes/<int:aluno_id>/notas/', notas_dependente, name='notas_dependente'),
]
