# Generated by Django 6.0.6 on 2026-06-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
