# Generated by Django 6.0.6 on 2026-06-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
