# Generated by Django 6.0.6 on 2026-06-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='tipo',
        ),
        migrations.AddField(
            model_name='perfil',
            name='bi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='morada',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
