# Generated by Django 6.0.6 on 2026-07-06 23:36

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_perfil_bi_alter_perfil_morada_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorUser',
            fields=[
            ],
            options={
                'verbose_name': 'Conta de Administrador',
                'verbose_name_plural': 'Contas de Administradores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AlunoUser',
            fields=[
            ],
            options={
                'verbose_name': 'Conta de Aluno',
                'verbose_name_plural': 'Contas de Alunos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EncarregadoUser',
            fields=[
            ],
            options={
                'verbose_name': 'Conta de Encarregado',
                'verbose_name_plural': 'Contas de Encarregados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorUser',
            fields=[
            ],
            options={
                'verbose_name': 'Conta de Professor',
                'verbose_name_plural': 'Contas de Professores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
