# Generated by Django 6.0.6 on 2026-08-10 04:00

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_administrador_subdiretor_pedagogico'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefeSecretariaUser',
            fields=[
            ],
            options={
                'verbose_name': 'Conta de Chefe de Secretaria',
                'verbose_name_plural': 'Contas de Chefes de Secretaria',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CoordenadorPaisUser',
            fields=[
            ],
            options={
                'verbose_name': 'Conta de Coordenador de Pais e Encarregados de Educação',
                'verbose_name_plural': 'Contas de Coordenadores de Pais e Encarregados de Educação',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CoordenadorTurnoUser',
            fields=[
            ],
            options={
                'verbose_name': 'Conta de Coordenador de Turno',
                'verbose_name_plural': 'Contas de Coordenadores de Turno',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DiretorGeralUser',
            fields=[
            ],
            options={
                'verbose_name': 'Conta de Diretor Geral',
                'verbose_name_plural': 'Contas de Diretores Gerais',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
