# Generated by Django 6.0.6 on 2026-08-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_criar_grupos_novos_papeis_administrativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='turno_coordenado',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], help_text='Aplicável apenas a contas de Coordenador de Turno — define quais Turmas (por turmas.Turma.periodo) esta conta supervisiona.', max_length=10, verbose_name='Turno coordenado'),
        ),
    ]
