# Generated by Django 6.0.6 on 2026-06-20 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_alter_professor_options_remove_professor_disciplinas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atribuicaodocente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='atribuicaodocente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
