# Generated by Django 6.0.6 on 2026-06-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0003_atribuicaodocente_ativo_atribuicaodocente_criado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='especialidade',
        ),
    ]
