# Generated by Django 6.0.6 on 2026-07-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0004_remove_professor_especialidade'),
        ('turmas', '0004_periodoacademico_data_fim_lancamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiretorTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.anoletivo')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Diretor de Turma',
                'verbose_name_plural': 'Diretores de Turma',
                'unique_together': {('turma', 'ano_letivo')},
            },
        ),
    ]
