# Generated by Django 6.0.6 on 2026-06-20 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frequencias', '0001_initial'),
        ('professores', '0002_alter_professor_options_remove_professor_disciplinas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='atribuicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.atribuicaodocente'),
        ),
        migrations.AddField(
            model_name='justificacaofalta',
            name='frequencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frequencias.frequencia'),
        ),
        migrations.AlterUniqueTogether(
            name='frequencia',
            unique_together={('aluno', 'atribuicao', 'data')},
        ),
    ]
