# Generated by Django 6.0.6 on 2026-08-10 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencias', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='justificacaofalta',
            name='analisada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='justificacaofalta',
            name='coordenador_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='justificacaofalta',
            name='parecer_coordenador',
            field=models.TextField(blank=True, verbose_name='Parecer do Coordenador de Turno'),
        ),
    ]
