# Generated by Django 6.0.6 on 2026-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_atualizado_em_aluno_criado_em'),
        ('pautas', '0003_nota_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadofinal',
            name='exame',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='mt1',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='mt2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='resultadofinal',
            name='mt3',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='resultadofinal',
            name='cf',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='resultadofinal',
            name='situacao',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('avaliacao', 'aluno')},
        ),
    ]
