# Generated by Django 6.0.6 on 2026-06-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_atualizado_em_aluno_criado_em'),
        ('disciplinas', '0002_disciplina_ativa'),
        ('pautas', '0004_resultadofinal_exame_resultadofinal_mt1_and_more'),
        ('turmas', '0003_turma_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt1', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('mt2', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('mt3', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('mf', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('exame', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('resultado', models.CharField(blank=True, max_length=30)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.anoletivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina')),
            ],
            options={
                'unique_together': {('aluno', 'disciplina', 'ano_letivo')},
            },
        ),
    ]
