# Generated by Django 6.0.6 on 2026-06-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0005_resultadodisciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadodisciplina',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
