# Generated by Django 6.0.6 on 2026-07-04 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0006_resultadodisciplina_nota_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='observacoes_validacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('com_erros', 'Com Erros'), ('validada', 'Validada')], default='rascunho', max_length=20),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='validado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultadodisciplina',
            name='observacoes_validacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resultadodisciplina',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('com_erros', 'Com Erros'), ('validada', 'Validada')], default='rascunho', max_length=20),
        ),
        migrations.AddField(
            model_name='resultadodisciplina',
            name='validado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadodisciplina',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
