# Generated by Django 6.0.6 on 2026-07-05 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_aluno_estado'),
        ('disciplinas', '0003_disciplina_nuclear'),
        ('pautas', '0007_avaliacao_observacoes_validacao_avaliacao_status_and_more'),
        ('turmas', '0006_turma_periodo_turma_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadodisciplina',
            name='nota_recurso',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Nota seca: quando preenchida, torna-se a nota final da disciplina.', max_digits=4, null=True, verbose_name='Nota de Recurso'),
        ),
        migrations.CreateModel(
            name='SituacaoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(blank=True, choices=[('Aprovado', 'Aprovado'), ('Aprovado por Compensação', 'Aprovado por Compensação'), ('Reprovado', 'Reprovado')], max_length=30)),
                ('calculado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.anoletivo')),
                ('disciplinas_em_deficiencia', models.ManyToManyField(blank=True, related_name='+', to='disciplinas.disciplina')),
            ],
            options={
                'verbose_name': 'Situação Anual',
                'verbose_name_plural': 'Situações Anuais',
                'unique_together': {('aluno', 'ano_letivo')},
            },
        ),
    ]
