# Generated by Django 6.0.6 on 2026-07-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0008_resultadodisciplina_nota_recurso_situacaoanual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='npp',
        ),
    ]
