# Generated by Django 6.0.6 on 2026-07-11 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_aluno_estado'),
        ('pautas', '0009_remove_nota_npp'),
        ('turmas', '0007_turma_numero_pauta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('boletim', 'Boletim de Notas'), ('certificado', 'Certificado')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Autorização'), ('recusado', 'Recusado'), ('autorizado', 'Autorizado - Aguarda Pagamento'), ('pagamento_submetido', 'Comprovativo Submetido'), ('pronto_levantamento', 'Pronto para Levantamento'), ('levantado', 'Levantado')], default='pendente', max_length=25)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_recusa', models.TextField(blank=True)),
                ('comprovativo_pagamento', models.ImageField(blank=True, null=True, upload_to='pagamentos/')),
                ('pagamento_submetido_em', models.DateTimeField(blank=True, null=True)),
                ('pagamento_confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.anoletivo')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pagamento_confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Documento',
                'verbose_name_plural': 'Pedidos de Documentos',
                'ordering': ['-solicitado_em'],
            },
        ),
    ]
