# Generated by Django 6.0.6 on 2026-07-25 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0010_pedidodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadodisciplina',
            name='en',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Só se aplica ao IIº Ano EJA — entra na MFED = MFD + (EN×0,40)/2.', max_digits=4, null=True, verbose_name='Exame Nacional'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='npt',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
