# Generated by Django 6.0.6 on 2026-08-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0011_resultadodisciplina_en_alter_nota_npt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodocumento',
            name='tipo',
            field=models.CharField(choices=[('boletim', 'Boletim de Notas'), ('declaracao', 'Declaração de Notas'), ('certificado', 'Certificado')], max_length=20),
        ),
    ]
