# Generated by Django 6.0.6 on 2026-08-11 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0013_resultadodisciplina_homologado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodocumento',
            name='autenticado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidodocumento',
            name='autenticado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autenticado por (Diretor Geral/Sub-diretor/Diretor de Turma)'),
        ),
        migrations.AddField(
            model_name='pedidodocumento',
            name='emitido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidodocumento',
            name='emitido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por (Secretaria)'),
        ),
        migrations.AddField(
            model_name='pedidodocumento',
            name='forma_pagamento',
            field=models.CharField(blank=True, help_text='Indicada pela Secretaria ao autorizar o pedido (ex.: Transferência GPS/Ruper, referência de pagamento).', max_length=150, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pedidodocumento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Autorização'), ('recusado', 'Recusado'), ('autorizado', 'Autorizado - Aguarda Pagamento'), ('pagamento_submetido', 'Comprovativo Submetido'), ('pagamento_confirmado', 'Pagamento Confirmado - Aguarda Emissão'), ('emitido', 'Emitido - Aguarda Autenticação'), ('autenticado', 'Autenticado - Aguarda Notificação'), ('pronto_levantamento', 'Pronto para Levantamento'), ('levantado', 'Levantado')], default='pendente', max_length=25),
        ),
    ]
