# Generated by Django 6.0.6 on 2026-06-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_alter_anoletivo_options_alter_classe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
