# Generated by Django 6.0.6 on 2026-07-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_turma_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoacademico',
            name='data_fim_lancamento',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do lançamento de notas'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='data_inicio_lancamento',
            field=models.DateField(blank=True, null=True, verbose_name='Início do lançamento de notas'),
        ),
    ]
