# Generated by Django 6.0.6 on 2026-07-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0005_seed_turmas_7_8_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='periodo',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10),
        ),
        migrations.AddField(
            model_name='turma',
            name='sala',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
