# Generated by Django 6.0.6 on 2026-07-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0006_turma_periodo_turma_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='numero_pauta',
            field=models.CharField(blank=True, help_text='Ex.: 03/2026 — usado no cabeçalho da pauta final impressa.', max_length=20, verbose_name='Nº da Pauta'),
        ),
    ]
