# Generated by Django 6.0.6 on 2026-07-19 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0006_backfill_grupo_professor'),
        ('turmas', '0007_turma_numero_pauta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira')], max_length=3)),
                ('tempo', models.PositiveSmallIntegerField(verbose_name='Tempo')),
                ('atribuicao', models.ForeignKey(blank=True, help_text='Deixe em branco para representar um tempo livre ("Borla").', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='professores.atribuicaodocente', verbose_name='Disciplina / Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Horário de Aula',
                'verbose_name_plural': 'Horários de Aula',
                'ordering': ['turma', 'dia_semana', 'tempo'],
                'unique_together': {('turma', 'dia_semana', 'tempo')},
            },
        ),
    ]
