# Generated by Django 6.0.6 on 2026-07-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_disciplina_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='nuclear',
            field=models.BooleanField(default=False, help_text='Disciplinas nucleares (Matemática, Língua Portuguesa) não têm direito a recurso.', verbose_name='Disciplina nuclear'),
        ),
    ]
