# Generated by Django 6.0.6 on 2026-07-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0004_marcar_disciplinas_nucleares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nuclear',
            field=models.BooleanField(default=False, help_text='Disciplinas nucleares (Matemática, Língua Portuguesa): nunca podem estar ambas em recurso ao mesmo tempo, e uma única ficar em 8/9 após o recurso já reprova o aluno (sem tolerância).', verbose_name='Disciplina nuclear'),
        ),
    ]
